// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/emojiGroupPremium" />
///</summary>
[TlObject(0x93bcf34)]
public sealed class TEmojiGroupPremium : IEmojiGroup
{
    public uint ConstructorId => 0x93bcf34;
    public string Title { get; set; }
    public long IconEmojiId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Title);
        writer.Write(IconEmojiId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Title = reader.ReadString();
        IconEmojiId = reader.ReadInt64();
    }
}