// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/emojiGroupGreeting" />
///</summary>
[TlObject(0x80d26cc7)]
public sealed class TEmojiGroupGreeting : IEmojiGroup
{
    public uint ConstructorId => 0x80d26cc7;
    public string Title { get; set; }
    public long IconEmojiId { get; set; }
    public TVector<string> Emoticons { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Title);
        writer.Write(IconEmojiId);
        writer.Write(Emoticons);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Title = reader.ReadString();
        IconEmojiId = reader.ReadInt64();
        Emoticons = reader.Read<TVector<string>>();
    }
}