// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/connectedBotStarRef" />
///</summary>
[TlObject(0x19a13f71)]
public sealed class TConnectedBotStarRef : IConnectedBotStarRef
{
    public uint ConstructorId => 0x19a13f71;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool Revoked { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public string Url { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int Date { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public long BotId { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int CommissionPermille { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int? DurationMonths { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public long Participants { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public long Revenue { get; set; }

    public void ComputeFlag()
    {
        if (Revoked) { Flags[1] = true; }
        if (/*DurationMonths != 0 && */DurationMonths.HasValue) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Url);
        writer.Write(Date);
        writer.Write(BotId);
        writer.Write(CommissionPermille);
        if (Flags[0]) { writer.Write(DurationMonths.Value); }
        writer.Write(Participants);
        writer.Write(Revenue);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[1]) { Revoked = true; }
        Url = reader.ReadString();
        Date = reader.ReadInt32();
        BotId = reader.ReadInt64();
        CommissionPermille = reader.ReadInt32();
        if (Flags[0]) { DurationMonths = reader.ReadInt32(); }
        Participants = reader.ReadInt64();
        Revenue = reader.ReadInt64();
    }
}