// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/contactBirthday" />
///</summary>
[TlObject(0x1d998733)]
public sealed class TContactBirthday : IContactBirthday
{
    public uint ConstructorId => 0x1d998733;
    public long ContactId { get; set; }
    public MyTelegram.Schema.IBirthday Birthday { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ContactId);
        writer.Write(Birthday);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ContactId = reader.ReadInt64();
        Birthday = reader.Read<MyTelegram.Schema.IBirthday>();
    }
}