// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Stats;

///<summary>
/// See <a href="https://corefork.telegram.org/method/stats.getBroadcastRevenueTransactions" />
///</summary>
[TlObject(0x69280f)]
public sealed class RequestGetBroadcastRevenueTransactions : IRequest<MyTelegram.Schema.Stats.IBroadcastRevenueTransactions>
{
    public uint ConstructorId => 0x69280f;
    public MyTelegram.Schema.IInputChannel Channel { get; set; }
    public int Offset { get; set; }
    public int Limit { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Channel);
        writer.Write(Offset);
        writer.Write(Limit);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Channel = reader.Read<MyTelegram.Schema.IInputChannel>();
        Offset = reader.ReadInt32();
        Limit = reader.ReadInt32();
    }
}
