// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Stats;

///<summary>
/// See <a href="https://corefork.telegram.org/method/stats.getBroadcastRevenueStats" />
///</summary>
[TlObject(0x75dfb671)]
public sealed class RequestGetBroadcastRevenueStats : IRequest<MyTelegram.Schema.Stats.IBroadcastRevenueStats>
{
    public uint ConstructorId => 0x75dfb671;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Dark { get; set; }
    public MyTelegram.Schema.IInputChannel Channel { get; set; }

    public void ComputeFlag()
    {
        if (Dark) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Channel);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Dark = true; }
        Channel = reader.Read<MyTelegram.Schema.IInputChannel>();
    }
}
