// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Stats;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/stats.broadcastRevenueWithdrawalUrl" />
///</summary>
[TlObject(0xec659737)]
public sealed class TBroadcastRevenueWithdrawalUrl : IBroadcastRevenueWithdrawalUrl
{
    public uint ConstructorId => 0xec659737;
    public string Url { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Url);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Url = reader.ReadString();
    }
}