// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Stats;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/stats.broadcastRevenueStats" />
///</summary>
[TlObject(0xd07b4bad)]
public sealed class TBroadcastRevenueStats : IBroadcastRevenueStats
{
    public uint ConstructorId => 0xd07b4bad;
    public MyTelegram.Schema.IStatsGraph TopHoursGraph { get; set; }
    public MyTelegram.Schema.IStatsGraph RevenueGraph { get; set; }
    public long CurrentBalance { get; set; }
    public long AvailableBalance { get; set; }
    public long OverallRevenue { get; set; }
    public double UsdRate { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(TopHoursGraph);
        writer.Write(RevenueGraph);
        writer.Write(CurrentBalance);
        writer.Write(AvailableBalance);
        writer.Write(OverallRevenue);
        writer.Write(UsdRate);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        TopHoursGraph = reader.Read<MyTelegram.Schema.IStatsGraph>();
        RevenueGraph = reader.Read<MyTelegram.Schema.IStatsGraph>();
        CurrentBalance = reader.ReadInt64();
        AvailableBalance = reader.ReadInt64();
        OverallRevenue = reader.ReadInt64();
        UsdRate = reader.ReadDouble();
    }
}