// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Stats;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/stats.broadcastRevenueTransactions" />
///</summary>
[TlObject(0x87158466)]
public sealed class TBroadcastRevenueTransactions : IBroadcastRevenueTransactions
{
    public uint ConstructorId => 0x87158466;
    public int Count { get; set; }
    public TVector<MyTelegram.Schema.IBroadcastRevenueTransaction> Transactions { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Count);
        writer.Write(Transactions);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Count = reader.ReadInt32();
        Transactions = reader.Read<TVector<MyTelegram.Schema.IBroadcastRevenueTransaction>>();
    }
}