// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Stats;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/stats.broadcastRevenueStats" />
///</summary>
[TlObject(0x5407e297)]
public sealed class TBroadcastRevenueStats : IBroadcastRevenueStats
{
    public uint ConstructorId => 0x5407e297;
    public MyTelegram.Schema.IStatsGraph TopHoursGraph { get; set; }
    public MyTelegram.Schema.IStatsGraph RevenueGraph { get; set; }
    public MyTelegram.Schema.IBroadcastRevenueBalances Balances { get; set; }
    public double UsdRate { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(TopHoursGraph);
        writer.Write(RevenueGraph);
        writer.Write(Balances);
        writer.Write(UsdRate);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        TopHoursGraph = reader.Read<MyTelegram.Schema.IStatsGraph>();
        RevenueGraph = reader.Read<MyTelegram.Schema.IStatsGraph>();
        Balances = reader.Read<MyTelegram.Schema.IBroadcastRevenueBalances>();
        UsdRate = reader.ReadDouble();
    }
}