// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Channels;

///<summary>
/// See <a href="https://corefork.telegram.org/method/channels.searchPosts" />
///</summary>
[TlObject(0xd19f987b)]
public sealed class RequestSearchPosts : IRequest<MyTelegram.Schema.Messages.IMessages>
{
    public uint ConstructorId => 0xd19f987b;
    ///<summary>
    /// &nbsp;
    ///</summary>
    public string Hashtag { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int OffsetRate { get; set; }

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/InputPeer" />
    ///</summary>
    public MyTelegram.Schema.IInputPeer OffsetPeer { get; set; }

    ///<summary>
    /// <a href="https://corefork.telegram.org/api/offsets">Offsets for pagination, for more info click here</a>
    ///</summary>
    public int OffsetId { get; set; }

    ///<summary>
    /// Maximum number of results to return, <a href="https://corefork.telegram.org/api/offsets">see pagination</a>
    ///</summary>
    public int Limit { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Hashtag);
        writer.Write(OffsetRate);
        writer.Write(OffsetPeer);
        writer.Write(OffsetId);
        writer.Write(Limit);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Hashtag = reader.ReadString();
        OffsetRate = reader.ReadInt32();
        OffsetPeer = reader.Read<MyTelegram.Schema.IInputPeer>();
        OffsetId = reader.ReadInt32();
        Limit = reader.ReadInt32();
    }
}
