// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Channels;

///<summary>
/// See <a href="https://corefork.telegram.org/method/channels.restrictSponsoredMessages" />
///</summary>
[TlObject(0x9ae91519)]
public sealed class RequestRestrictSponsoredMessages : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x9ae91519;
    public MyTelegram.Schema.IInputChannel Channel { get; set; }
    public bool Restricted { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Channel);
        writer.Write(Restricted);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Channel = reader.Read<MyTelegram.Schema.IInputChannel>();
        Restricted = reader.Read();
    }
}
