// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Channels;

///<summary>
/// Informs the server that the user has either:
/// <para>Possible errors</para>
/// Code Type Description
/// 400 CHANNEL_INVALID The provided channel is invalid.
/// See <a href="https://corefork.telegram.org/method/channels.clickSponsoredMessage" />
///</summary>
[TlObject(0x1445d75)]
public sealed class RequestClickSponsoredMessage : IRequest<IBool>
{
    public uint ConstructorId => 0x1445d75;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Media { get; set; }
    public bool Fullscreen { get; set; }

    ///<summary>
    /// Channel where the sponsored message was posted
    /// See <a href="https://corefork.telegram.org/type/InputChannel" />
    ///</summary>
    public MyTelegram.Schema.IInputChannel Channel { get; set; }

    ///<summary>
    /// Message ID
    ///</summary>
    public byte[] RandomId { get; set; }

    public void ComputeFlag()
    {
        if (Media) { Flags[0] = true; }
        if (Fullscreen) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Channel);
        writer.Write(RandomId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Media = true; }
        if (Flags[1]) { Fullscreen = true; }
        Channel = reader.Read<MyTelegram.Schema.IInputChannel>();
        RandomId = reader.ReadBytes();
    }
}
