// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Channels;

///<summary>
/// See <a href="https://corefork.telegram.org/method/channels.reportSponsoredMessage" />
///</summary>
[TlObject(0xaf8ff6b9)]
public sealed class RequestReportSponsoredMessage : IRequest<MyTelegram.Schema.Channels.ISponsoredMessageReportResult>
{
    public uint ConstructorId => 0xaf8ff6b9;
    public MyTelegram.Schema.IInputChannel Channel { get; set; }
    public byte[] RandomId { get; set; }
    public byte[] Option { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Channel);
        writer.Write(RandomId);
        writer.Write(Option);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Channel = reader.Read<MyTelegram.Schema.IInputChannel>();
        RandomId = reader.ReadBytes();
        Option = reader.ReadBytes();
    }
}
