// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Smsjobs;

///<summary>
/// See <a href="https://corefork.telegram.org/method/smsjobs.getSmsJob" />
///</summary>
[TlObject(0x778d902f)]
public sealed class RequestGetSmsJob : IRequest<MyTelegram.Schema.ISmsJob>
{
    public uint ConstructorId => 0x778d902f;
    public string JobId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(JobId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        JobId = reader.ReadString();
    }
}
