// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messageReportOption" />
///</summary>
[TlObject(0x7903e3d9)]
public sealed class TMessageReportOption : IMessageReportOption
{
    public uint ConstructorId => 0x7903e3d9;
    public string Text { get; set; }
    public byte[] Option { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Text);
        writer.Write(Option);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Text = reader.ReadString();
        Option = reader.ReadBytes();
    }
}