// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/timezone" />
///</summary>
[TlObject(0xff9289f5)]
public sealed class TTimezone : ITimezone
{
    public uint ConstructorId => 0xff9289f5;
    public string Id { get; set; }
    public string Name { get; set; }
    public int UtcOffset { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Id);
        writer.Write(Name);
        writer.Write(UtcOffset);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Id = reader.ReadString();
        Name = reader.ReadString();
        UtcOffset = reader.ReadInt32();
    }
}