// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/broadcastRevenueTransactionRefund" />
///</summary>
[TlObject(0x42d30d2e)]
public sealed class TBroadcastRevenueTransactionRefund : IBroadcastRevenueTransaction
{
    public uint ConstructorId => 0x42d30d2e;
    public long Amount { get; set; }
    public int Date { get; set; }
    public string Provider { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Amount);
        writer.Write(Date);
        writer.Write(Provider);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Amount = reader.ReadInt64();
        Date = reader.ReadInt32();
        Provider = reader.ReadString();
    }
}