// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/broadcastRevenueTransactionProceeds" />
///</summary>
[TlObject(0x557e2cc4)]
public sealed class TBroadcastRevenueTransactionProceeds : IBroadcastRevenueTransaction
{
    public uint ConstructorId => 0x557e2cc4;
    public long Amount { get; set; }
    public int FromDate { get; set; }
    public int ToDate { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Amount);
        writer.Write(FromDate);
        writer.Write(ToDate);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Amount = reader.ReadInt64();
        FromDate = reader.ReadInt32();
        ToDate = reader.ReadInt32();
    }
}