// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/prepaidStarsGiveaway" />
///</summary>
[TlObject(0x9a9d77e0)]
public sealed class TPrepaidStarsGiveaway : IPrepaidGiveaway
{
    public uint ConstructorId => 0x9a9d77e0;
    public long Id { get; set; }
    public long Stars { get; set; }
    public int Quantity { get; set; }
    public int Boosts { get; set; }
    public int Date { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Id);
        writer.Write(Stars);
        writer.Write(Quantity);
        writer.Write(Boosts);
        writer.Write(Date);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Id = reader.ReadInt64();
        Stars = reader.ReadInt64();
        Quantity = reader.ReadInt32();
        Boosts = reader.ReadInt32();
        Date = reader.ReadInt32();
    }
}