// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getStarsSubscriptions" />
///</summary>
[TlObject(0x32512c5)]
public sealed class RequestGetStarsSubscriptions : IRequest<MyTelegram.Schema.Payments.IStarsStatus>
{
    public uint ConstructorId => 0x32512c5;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool MissingBalance { get; set; }
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public string Offset { get; set; }

    public void ComputeFlag()
    {
        if (MissingBalance) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
        writer.Write(Offset);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { MissingBalance = true; }
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        Offset = reader.ReadString();
    }
}
