// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getStarsTopupOptions" />
///</summary>
[TlObject(0xc00ec7d3)]
public sealed class RequestGetStarsTopupOptions : IRequest<TVector<MyTelegram.Schema.IStarsTopupOption>>
{
    public uint ConstructorId => 0xc00ec7d3;

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}
