// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.convertStarGift" />
///</summary>
[TlObject(0x421e027)]
public sealed class RequestConvertStarGift : IRequest<IBool>
{
    public uint ConstructorId => 0x421e027;
    public MyTelegram.Schema.IInputUser UserId { get; set; }
    public int MsgId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(UserId);
        writer.Write(MsgId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        UserId = reader.Read<MyTelegram.Schema.IInputUser>();
        MsgId = reader.ReadInt32();
    }
}
