// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getStarsGiveawayOptions" />
///</summary>
[TlObject(0xbd1efd3e)]
public sealed class RequestGetStarsGiveawayOptions : IRequest<TVector<MyTelegram.Schema.IStarsGiveawayOption>>
{
    public uint ConstructorId => 0xbd1efd3e;

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}
