// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getStarsRevenueStats" />
///</summary>
[TlObject(0xd91ffad6)]
public sealed class RequestGetStarsRevenueStats : IRequest<MyTelegram.Schema.Payments.IStarsRevenueStats>
{
    public uint ConstructorId => 0xd91ffad6;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Dark { get; set; }
    public MyTelegram.Schema.IInputPeer Peer { get; set; }

    public void ComputeFlag()
    {
        if (Dark) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Dark = true; }
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
    }
}
