// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.changeStarsSubscription" />
///</summary>
[TlObject(0xc7770878)]
public sealed class RequestChangeStarsSubscription : IRequest<IBool>
{
    public uint ConstructorId => 0xc7770878;
    public BitArray Flags { get; set; } = new BitArray(32);
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public string SubscriptionId { get; set; }
    public bool? Canceled { get; set; }

    public void ComputeFlag()
    {
        if (Canceled !=null) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
        writer.Write(SubscriptionId);
        if (Flags[0]) { writer.Write(Canceled.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        SubscriptionId = reader.ReadString();
        if (Flags[0]) { Canceled = reader.Read(); }
    }
}
