// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getStarGifts" />
///</summary>
[TlObject(0xc4563590)]
public sealed class RequestGetStarGifts : IRequest<MyTelegram.Schema.Payments.IStarGifts>
{
    public uint ConstructorId => 0xc4563590;
    public int Hash { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Hash);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Hash = reader.ReadInt32();
    }
}
