// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getConnectedStarRefBots" />
///</summary>
[TlObject(0x5869a553)]
public sealed class RequestGetConnectedStarRefBots : IRequest<MyTelegram.Schema.Payments.IConnectedStarRefBots>
{
    public uint ConstructorId => 0x5869a553;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/InputPeer" />
    ///</summary>
    public MyTelegram.Schema.IInputPeer Peer { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int? OffsetDate { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public string? OffsetLink { get; set; }

    ///<summary>
    /// Maximum number of results to return, <a href="https://corefork.telegram.org/api/offsets">see pagination</a>
    ///</summary>
    public int Limit { get; set; }

    public void ComputeFlag()
    {
        if (/*OffsetDate != 0 && */OffsetDate.HasValue) { Flags[2] = true; }
        if (OffsetLink != null) { Flags[2] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
        if (Flags[2]) { writer.Write(OffsetDate.Value); }
        if (Flags[2]) { writer.Write(OffsetLink); }
        writer.Write(Limit);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        if (Flags[2]) { OffsetDate = reader.ReadInt32(); }
        if (Flags[2]) { OffsetLink = reader.ReadString(); }
        Limit = reader.ReadInt32();
    }
}
