// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// Receipt for <a href="https://corefork.telegram.org/api/stars">payment made using Telegram Stars</a>.
/// See <a href="https://corefork.telegram.org/constructor/payments.paymentReceiptStars" />
///</summary>
[TlObject(0xdabbf83a)]
public sealed class TPaymentReceiptStars : IPaymentReceipt
{
    public uint ConstructorId => 0xdabbf83a;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// Date of generation
    ///</summary>
    public int Date { get; set; }

    ///<summary>
    /// Bot ID
    ///</summary>
    public long BotId { get; set; }

    ///<summary>
    /// Title
    ///</summary>
    public string Title { get; set; }

    ///<summary>
    /// Description
    ///</summary>
    public string Description { get; set; }

    ///<summary>
    /// Product photo
    /// See <a href="https://corefork.telegram.org/type/WebDocument" />
    ///</summary>
    public MyTelegram.Schema.IWebDocument? Photo { get; set; }

    ///<summary>
    /// Invoice
    /// See <a href="https://corefork.telegram.org/type/Invoice" />
    ///</summary>
    public MyTelegram.Schema.IInvoice Invoice { get; set; }

    ///<summary>
    /// Currency, always <code>XTR</code>.
    ///</summary>
    public string Currency { get; set; }

    ///<summary>
    /// Amount of <a href="https://corefork.telegram.org/api/stars">Telegram Stars</a>.
    ///</summary>
    public long TotalAmount { get; set; }

    ///<summary>
    /// Transaction ID
    ///</summary>
    public string TransactionId { get; set; }

    ///<summary>
    /// Info about users mentioned in the other fields.
    ///</summary>
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {
        if (Photo != null) { Flags[2] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Date);
        writer.Write(BotId);
        writer.Write(Title);
        writer.Write(Description);
        if (Flags[2]) { writer.Write(Photo); }
        writer.Write(Invoice);
        writer.Write(Currency);
        writer.Write(TotalAmount);
        writer.Write(TransactionId);
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Date = reader.ReadInt32();
        BotId = reader.ReadInt64();
        Title = reader.ReadString();
        Description = reader.ReadString();
        if (Flags[2]) { Photo = reader.Read<MyTelegram.Schema.IWebDocument>(); }
        Invoice = reader.Read<MyTelegram.Schema.IInvoice>();
        Currency = reader.ReadString();
        TotalAmount = reader.ReadInt64();
        TransactionId = reader.ReadString();
        Users = reader.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}