// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/payments.starGifts" />
///</summary>
[TlObject(0x901689ea)]
public sealed class TStarGifts : IStarGifts
{
    public uint ConstructorId => 0x901689ea;
    public int Hash { get; set; }
    public TVector<MyTelegram.Schema.IStarGift> Gifts { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Hash);
        writer.Write(Gifts);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Hash = reader.ReadInt32();
        Gifts = reader.Read<TVector<MyTelegram.Schema.IStarGift>>();
    }
}