// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/payments.starsRevenueStats" />
///</summary>
[TlObject(0xc92bb73b)]
public sealed class TStarsRevenueStats : IStarsRevenueStats
{
    public uint ConstructorId => 0xc92bb73b;
    public MyTelegram.Schema.IStatsGraph RevenueGraph { get; set; }
    public MyTelegram.Schema.IStarsRevenueStatus Status { get; set; }
    public double UsdRate { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(RevenueGraph);
        writer.Write(Status);
        writer.Write(UsdRate);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        RevenueGraph = reader.Read<MyTelegram.Schema.IStatsGraph>();
        Status = reader.Read<MyTelegram.Schema.IStarsRevenueStatus>();
        UsdRate = reader.ReadDouble();
    }
}