// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// <a href="https://corefork.telegram.org/api/gifts">Gifts</a> displayed on a user's profile.
/// See <a href="https://corefork.telegram.org/constructor/payments.userStarGifts" />
///</summary>
[TlObject(0x6b65b517)]
public sealed class TUserStarGifts : IUserStarGifts
{
    public uint ConstructorId => 0x6b65b517;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// Total number of gifts displayed on the profile.
    ///</summary>
    public int Count { get; set; }

    ///<summary>
    /// The gifts.
    ///</summary>
    public TVector<MyTelegram.Schema.IUserStarGift> Gifts { get; set; }

    ///<summary>
    /// Offset for <a href="https://corefork.telegram.org/api/offsets">pagination</a>.
    ///</summary>
    public string? NextOffset { get; set; }

    ///<summary>
    /// Users mentioned in the <code>gifts</code> vector.
    ///</summary>
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {
        if (NextOffset != null) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Count);
        writer.Write(Gifts);
        if (Flags[0]) { writer.Write(NextOffset); }
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Count = reader.ReadInt32();
        Gifts = reader.Read<TVector<MyTelegram.Schema.IUserStarGift>>();
        if (Flags[0]) { NextOffset = reader.ReadString(); }
        Users = reader.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}