// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/payments.userStarGifts" />
///</summary>
[TlObject(0x6b65b517)]
public sealed class TUserStarGifts : IUserStarGifts
{
    public uint ConstructorId => 0x6b65b517;
    public BitArray Flags { get; set; } = new BitArray(32);
    public int Count { get; set; }
    public TVector<MyTelegram.Schema.IUserStarGift> Gifts { get; set; }
    public string? NextOffset { get; set; }
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {
        if (NextOffset != null) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Count);
        writer.Write(Gifts);
        if (Flags[0]) { writer.Write(NextOffset); }
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Count = reader.ReadInt32();
        Gifts = reader.Read<TVector<MyTelegram.Schema.IUserStarGift>>();
        if (Flags[0]) { NextOffset = reader.ReadString(); }
        Users = reader.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}