// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Fragment;

///<summary>
/// See <a href="https://corefork.telegram.org/method/fragment.getCollectibleInfo" />
///</summary>
[TlObject(0xbe1e85ba)]
public sealed class RequestGetCollectibleInfo : IRequest<MyTelegram.Schema.Fragment.ICollectibleInfo>
{
    public uint ConstructorId => 0xbe1e85ba;
    public MyTelegram.Schema.IInputCollectible Collectible { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Collectible);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Collectible = reader.Read<MyTelegram.Schema.IInputCollectible>();
    }
}
