// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Fragment;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/fragment.collectibleInfo" />
///</summary>
[TlObject(0x6ebdff91)]
public sealed class TCollectibleInfo : ICollectibleInfo
{
    public uint ConstructorId => 0x6ebdff91;
    public int PurchaseDate { get; set; }
    public string Currency { get; set; }
    public long Amount { get; set; }
    public string CryptoCurrency { get; set; }
    public long CryptoAmount { get; set; }
    public string Url { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(PurchaseDate);
        writer.Write(Currency);
        writer.Write(Amount);
        writer.Write(CryptoCurrency);
        writer.Write(CryptoAmount);
        writer.Write(Url);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        PurchaseDate = reader.ReadInt32();
        Currency = reader.ReadString();
        Amount = reader.ReadInt64();
        CryptoCurrency = reader.ReadString();
        CryptoAmount = reader.ReadInt64();
        Url = reader.ReadString();
    }
}