// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/channelAdminLogEventActionToggleSignatureProfiles" />
///</summary>
[TlObject(0x60a79c79)]
public sealed class TChannelAdminLogEventActionToggleSignatureProfiles : IChannelAdminLogEventAction
{
    public uint ConstructorId => 0x60a79c79;
    public bool NewValue { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(NewValue);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        NewValue = reader.Read();
    }
}