// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/channelAdminLogEventActionParticipantSubExtend" />
///</summary>
[TlObject(0x64642db3)]
public sealed class TChannelAdminLogEventActionParticipantSubExtend : IChannelAdminLogEventAction
{
    public uint ConstructorId => 0x64642db3;
    public MyTelegram.Schema.IChannelParticipant PrevParticipant { get; set; }
    public MyTelegram.Schema.IChannelParticipant NewParticipant { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(PrevParticipant);
        writer.Write(NewParticipant);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        PrevParticipant = reader.Read<MyTelegram.Schema.IChannelParticipant>();
        NewParticipant = reader.Read<MyTelegram.Schema.IChannelParticipant>();
    }
}