// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/businessGreetingMessage" />
///</summary>
[TlObject(0xe519abab)]
public sealed class TBusinessGreetingMessage : IBusinessGreetingMessage
{
    public uint ConstructorId => 0xe519abab;
    public int ShortcutId { get; set; }
    public MyTelegram.Schema.IBusinessRecipients Recipients { get; set; }
    public int NoActivityDays { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ShortcutId);
        writer.Write(Recipients);
        writer.Write(NoActivityDays);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ShortcutId = reader.ReadInt32();
        Recipients = reader.Read<MyTelegram.Schema.IBusinessRecipients>();
        NoActivityDays = reader.ReadInt32();
    }
}