// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/birthday" />
///</summary>
[TlObject(0x6c8e1e06)]
public sealed class TBirthday : IBirthday
{
    public uint ConstructorId => 0x6c8e1e06;
    public BitArray Flags { get; set; } = new BitArray(32);
    public int Day { get; set; }
    public int Month { get; set; }
    public int? Year { get; set; }

    public void ComputeFlag()
    {
        if (/*Year != 0 && */Year.HasValue) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Day);
        writer.Write(Month);
        if (Flags[0]) { writer.Write(Year.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Day = reader.ReadInt32();
        Month = reader.ReadInt32();
        if (Flags[0]) { Year = reader.ReadInt32(); }
    }
}