// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Contains the webview URL with appropriate theme and user info parameters added
/// See <a href="https://corefork.telegram.org/constructor/webViewResultUrl" />
///</summary>
[TlObject(0x4d22ff98)]
public sealed class TWebViewResultUrl : IWebViewResult
{
    public uint ConstructorId => 0x4d22ff98;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// If set, the app must be opened in fullsize mode instead of compact mode.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool Fullsize { get; set; }

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool Fullscreen { get; set; }

    ///<summary>
    /// Webview session ID (only returned by <a href="https://corefork.telegram.org/api/bots/webapps#inline-button-mini-apps">inline button mini apps</a>, <a href="https://corefork.telegram.org/api/bots/webapps#menu-button-mini-apps">menu button mini apps</a>, <a href="https://corefork.telegram.org/api/bots/webapps#attachment-menu-mini-apps">attachment menu mini apps</a>).
    ///</summary>
    public long? QueryId { get; set; }

    ///<summary>
    /// Webview URL to open
    ///</summary>
    public string Url { get; set; }

    public void ComputeFlag()
    {
        if (Fullsize) { Flags[1] = true; }
        if (Fullscreen) { Flags[2] = true; }
        if (/*QueryId != 0 &&*/ QueryId.HasValue) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[0]) { writer.Write(QueryId.Value); }
        writer.Write(Url);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[1]) { Fullsize = true; }
        if (Flags[2]) { Fullscreen = true; }
        if (Flags[0]) { QueryId = reader.ReadInt64(); }
        Url = reader.ReadString();
    }
}