// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputPrivacyValueAllowPremium" />
///</summary>
[TlObject(0x77cdc9f1)]
public sealed class TInputPrivacyValueAllowPremium : IInputPrivacyRule
{
    public uint ConstructorId => 0x77cdc9f1;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}