// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Official clients only, invoke with Apple push verification.
/// See <a href="https://corefork.telegram.org/method/invokeWithApnsSecret" />
///</summary>
[TlObject(0x0dae54f8)]
public sealed class RequestInvokeWithApnsSecret : IRequest<IObject>, IHasSubQuery
{
    public uint ConstructorId => 0x0dae54f8;
    ///<summary>
    /// Nonce.
    ///</summary>
    public string Nonce { get; set; }

    ///<summary>
    /// Secret.
    ///</summary>
    public string Secret { get; set; }

    ///<summary>
    /// Query.
    ///</summary>
    public IObject Query { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Nonce);
        writer.Write(Secret);
        writer.Write(Query);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Nonce = reader.ReadString();
        Secret = reader.ReadString();
        Query = reader.Read<IObject>();
    }
}
