// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/method/account.updateBusinessWorkHours" />
///</summary>
[TlObject(0x4b00e066)]
public sealed class RequestUpdateBusinessWorkHours : IRequest<IBool>
{
    public uint ConstructorId => 0x4b00e066;
    public BitArray Flags { get; set; } = new BitArray(32);
    public MyTelegram.Schema.IBusinessWorkHours? BusinessWorkHours { get; set; }

    public void ComputeFlag()
    {
        if (BusinessWorkHours != null) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[0]) { writer.Write(BusinessWorkHours); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { BusinessWorkHours = reader.Read<MyTelegram.Schema.IBusinessWorkHours>(); }
    }
}
