// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/method/account.setReactionsNotifySettings" />
///</summary>
[TlObject(0x316ce548)]
public sealed class RequestSetReactionsNotifySettings : IRequest<MyTelegram.Schema.IReactionsNotifySettings>
{
    public uint ConstructorId => 0x316ce548;
    public MyTelegram.Schema.IReactionsNotifySettings Settings { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Settings);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Settings = reader.Read<MyTelegram.Schema.IReactionsNotifySettings>();
    }
}
