// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/method/account.getBotBusinessConnection" />
///</summary>
[TlObject(0x76a86270)]
public sealed class RequestGetBotBusinessConnection : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x76a86270;
    public string ConnectionId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ConnectionId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ConnectionId = reader.ReadString();
    }
}
