// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/method/account.updateBusinessIntro" />
///</summary>
[TlObject(0xa614d034)]
public sealed class RequestUpdateBusinessIntro : IRequest<IBool>
{
    public uint ConstructorId => 0xa614d034;
    public BitArray Flags { get; set; } = new BitArray(32);
    public MyTelegram.Schema.IInputBusinessIntro? Intro { get; set; }

    public void ComputeFlag()
    {
        if (Intro != null) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[0]) { writer.Write(Intro); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Intro = reader.Read<MyTelegram.Schema.IInputBusinessIntro>(); }
    }
}
