// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/method/account.updateBusinessLocation" />
///</summary>
[TlObject(0x9e6b131a)]
public sealed class RequestUpdateBusinessLocation : IRequest<IBool>
{
    public uint ConstructorId => 0x9e6b131a;
    public BitArray Flags { get; set; } = new BitArray(32);
    public MyTelegram.Schema.IInputGeoPoint? GeoPoint { get; set; }
    public string? Address { get; set; }

    public void ComputeFlag()
    {
        if (GeoPoint != null) { Flags[1] = true; }
        if (Address != null) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[1]) { writer.Write(GeoPoint); }
        if (Flags[0]) { writer.Write(Address); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[1]) { GeoPoint = reader.Read<MyTelegram.Schema.IInputGeoPoint>(); }
        if (Flags[0]) { Address = reader.ReadString(); }
    }
}
