// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/method/account.updateBirthday" />
///</summary>
[TlObject(0xcc6e0c11)]
public sealed class RequestUpdateBirthday : IRequest<IBool>
{
    public uint ConstructorId => 0xcc6e0c11;
    public BitArray Flags { get; set; } = new BitArray(32);
    public MyTelegram.Schema.IBirthday? Birthday { get; set; }

    public void ComputeFlag()
    {
        if (Birthday != null) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[0]) { writer.Write(Birthday); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Birthday = reader.Read<MyTelegram.Schema.IBirthday>(); }
    }
}
