// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/method/account.toggleConnectedBotPaused" />
///</summary>
[TlObject(0x646e1097)]
public sealed class RequestToggleConnectedBotPaused : IRequest<IBool>
{
    public uint ConstructorId => 0x646e1097;
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public bool Paused { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(Paused);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        Paused = reader.Read();
    }
}
