// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starsRevenueStatus" />
///</summary>
[TlObject(0x79342946)]
public sealed class TStarsRevenueStatus : IStarsRevenueStatus
{
    public uint ConstructorId => 0x79342946;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool WithdrawalEnabled { get; set; }
    public long CurrentBalance { get; set; }
    public long AvailableBalance { get; set; }
    public long OverallRevenue { get; set; }
    public int? NextWithdrawalAt { get; set; }

    public void ComputeFlag()
    {
        if (WithdrawalEnabled) { Flags[0] = true; }
        if (/*NextWithdrawalAt != 0 && */NextWithdrawalAt.HasValue) { Flags[1] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(CurrentBalance);
        writer.Write(AvailableBalance);
        writer.Write(OverallRevenue);
        if (Flags[1]) { writer.Write(NextWithdrawalAt.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { WithdrawalEnabled = true; }
        CurrentBalance = reader.ReadInt64();
        AvailableBalance = reader.ReadInt64();
        OverallRevenue = reader.ReadInt64();
        if (Flags[1]) { NextWithdrawalAt = reader.ReadInt32(); }
    }
}