// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.editQuickReplyShortcut" />
///</summary>
[TlObject(0x5c003cef)]
public sealed class RequestEditQuickReplyShortcut : IRequest<IBool>
{
    public uint ConstructorId => 0x5c003cef;
    public int ShortcutId { get; set; }
    public string Shortcut { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ShortcutId);
        writer.Write(Shortcut);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ShortcutId = reader.ReadInt32();
        Shortcut = reader.ReadString();
    }
}
