// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.getEmojiStickerGroups" />
///</summary>
[TlObject(0x1dd840f5)]
public sealed class RequestGetEmojiStickerGroups : IRequest<MyTelegram.Schema.Messages.IEmojiGroups>
{
    public uint ConstructorId => 0x1dd840f5;
    public int Hash { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Hash);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Hash = reader.ReadInt32();
    }
}
