// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.getMyStickers" />
///</summary>
[TlObject(0xd0b5e1fc)]
public sealed class RequestGetMyStickers : IRequest<MyTelegram.Schema.Messages.IMyStickers>
{
    public uint ConstructorId => 0xd0b5e1fc;
    public long OffsetId { get; set; }
    public int Limit { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(OffsetId);
        writer.Write(Limit);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        OffsetId = reader.ReadInt64();
        Limit = reader.ReadInt32();
    }
}
