// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.clickSponsoredMessage" />
///</summary>
[TlObject(0xf093465)]
public sealed class RequestClickSponsoredMessage : IRequest<IBool>
{
    public uint ConstructorId => 0xf093465;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Media { get; set; }
    public bool Fullscreen { get; set; }
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public byte[] RandomId { get; set; }

    public void ComputeFlag()
    {
        if (Media) { Flags[0] = true; }
        if (Fullscreen) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
        writer.Write(RandomId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Media = true; }
        if (Flags[1]) { Fullscreen = true; }
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        RandomId = reader.ReadBytes();
    }
}
