// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.getQuickReplyMessages" />
///</summary>
[TlObject(0x94a495c3)]
public sealed class RequestGetQuickReplyMessages : IRequest<MyTelegram.Schema.Messages.IMessages>
{
    public uint ConstructorId => 0x94a495c3;
    public BitArray Flags { get; set; } = new BitArray(32);
    public int ShortcutId { get; set; }
    public TVector<int>? Id { get; set; }
    public long Hash { get; set; }

    public void ComputeFlag()
    {
        if (Id?.Count > 0) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(ShortcutId);
        if (Flags[0]) { writer.Write(Id); }
        writer.Write(Hash);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        ShortcutId = reader.ReadInt32();
        if (Flags[0]) { Id = reader.Read<TVector<int>>(); }
        Hash = reader.ReadInt64();
    }
}
