// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.toggleDialogFilterTags" />
///</summary>
[TlObject(0xfd2dda49)]
public sealed class RequestToggleDialogFilterTags : IRequest<IBool>
{
    public uint ConstructorId => 0xfd2dda49;
    public bool Enabled { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Enabled);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Enabled = reader.Read();
    }
}
