// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.deleteQuickReplyShortcut" />
///</summary>
[TlObject(0x3cc04740)]
public sealed class RequestDeleteQuickReplyShortcut : IRequest<IBool>
{
    public uint ConstructorId => 0x3cc04740;
    public int ShortcutId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ShortcutId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ShortcutId = reader.ReadInt32();
    }
}
