// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.sendPaidReaction" />
///</summary>
[TlObject(0x9dd6a67b)]
public sealed class RequestSendPaidReaction : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x9dd6a67b;
    public BitArray Flags { get; set; } = new BitArray(32);
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public int MsgId { get; set; }
    public int Count { get; set; }
    public long RandomId { get; set; }
    public bool? Private { get; set; }

    public void ComputeFlag()
    {
        if (Private !=null) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
        writer.Write(MsgId);
        writer.Write(Count);
        writer.Write(RandomId);
        if (Flags[0]) { writer.Write(Private.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        MsgId = reader.ReadInt32();
        Count = reader.ReadInt32();
        RandomId = reader.ReadInt64();
        if (Flags[0]) { Private = reader.Read(); }
    }
}
