// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.reportSponsoredMessage" />
///</summary>
[TlObject(0x1af3dbb8)]
public sealed class RequestReportSponsoredMessage : IRequest<MyTelegram.Schema.Channels.ISponsoredMessageReportResult>
{
    public uint ConstructorId => 0x1af3dbb8;
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public byte[] RandomId { get; set; }
    public byte[] Option { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(RandomId);
        writer.Write(Option);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        RandomId = reader.ReadBytes();
        Option = reader.ReadBytes();
    }
}
