// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.sendQuickReplyMessages" />
///</summary>
[TlObject(0x6c750de1)]
public sealed class RequestSendQuickReplyMessages : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x6c750de1;
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public int ShortcutId { get; set; }
    public TVector<int> Id { get; set; }
    public TVector<long> RandomId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(ShortcutId);
        writer.Write(Id);
        writer.Write(RandomId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        ShortcutId = reader.ReadInt32();
        Id = reader.Read<TVector<int>>();
        RandomId = reader.Read<TVector<long>>();
    }
}
