// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.getPaidReactionPrivacy" />
///</summary>
[TlObject(0x472455aa)]
public sealed class RequestGetPaidReactionPrivacy : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x472455aa;

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}
