// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.savePreparedInlineMessage" />
///</summary>
[TlObject(0xf21f7f2f)]
public sealed class RequestSavePreparedInlineMessage : IRequest<MyTelegram.Schema.Messages.IBotPreparedInlineMessage>
{
    public uint ConstructorId => 0xf21f7f2f;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/InputBotInlineResult" />
    ///</summary>
    public MyTelegram.Schema.IInputBotInlineResult Result { get; set; }

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/InputUser" />
    ///</summary>
    public MyTelegram.Schema.IInputUser UserId { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public TVector<MyTelegram.Schema.IInlineQueryPeerType>? PeerTypes { get; set; }

    public void ComputeFlag()
    {
        if (PeerTypes?.Count > 0) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Result);
        writer.Write(UserId);
        if (Flags[0]) { writer.Write(PeerTypes); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Result = reader.Read<MyTelegram.Schema.IInputBotInlineResult>();
        UserId = reader.Read<MyTelegram.Schema.IInputUser>();
        if (Flags[0]) { PeerTypes = reader.Read<TVector<MyTelegram.Schema.IInlineQueryPeerType>>(); }
    }
}
