// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.checkQuickReplyShortcut" />
///</summary>
[TlObject(0xf1d0fbd3)]
public sealed class RequestCheckQuickReplyShortcut : IRequest<IBool>
{
    public uint ConstructorId => 0xf1d0fbd3;
    public string Shortcut { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Shortcut);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Shortcut = reader.ReadString();
    }
}
