// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.reorderQuickReplies" />
///</summary>
[TlObject(0x60331907)]
public sealed class RequestReorderQuickReplies : IRequest<IBool>
{
    public uint ConstructorId => 0x60331907;
    public TVector<int> Order { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Order);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Order = reader.Read<TVector<int>>();
    }
}
