// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messages.dialogFilters" />
///</summary>
[TlObject(0x2ad93719)]
public sealed class TDialogFilters : IDialogFilters
{
    public uint ConstructorId => 0x2ad93719;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool TagsEnabled { get; set; }
    public TVector<MyTelegram.Schema.IDialogFilter> Filters { get; set; }

    public void ComputeFlag()
    {
        if (TagsEnabled) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Filters);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { TagsEnabled = true; }
        Filters = reader.Read<TVector<MyTelegram.Schema.IDialogFilter>>();
    }
}