// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messages.invitedUsers" />
///</summary>
[TlObject(0x7f5defa6)]
public sealed class TInvitedUsers : IInvitedUsers
{
    public uint ConstructorId => 0x7f5defa6;
    public MyTelegram.Schema.IUpdates Updates { get; set; }
    public TVector<MyTelegram.Schema.IMissingInvitee> MissingInvitees { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Updates);
        writer.Write(MissingInvitees);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Updates = reader.Read<MyTelegram.Schema.IUpdates>();
        MissingInvitees = reader.Read<TVector<MyTelegram.Schema.IMissingInvitee>>();
    }
}