// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messages.myStickers" />
///</summary>
[TlObject(0xfaff629d)]
public sealed class TMyStickers : IMyStickers
{
    public uint ConstructorId => 0xfaff629d;
    public int Count { get; set; }
    public TVector<MyTelegram.Schema.IStickerSetCovered> Sets { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Count);
        writer.Write(Sets);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Count = reader.ReadInt32();
        Sets = reader.Read<TVector<MyTelegram.Schema.IStickerSetCovered>>();
    }
}