// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/missingInvitee" />
///</summary>
[TlObject(0x628c9224)]
public sealed class TMissingInvitee : IMissingInvitee
{
    public uint ConstructorId => 0x628c9224;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool PremiumWouldAllowInvite { get; set; }
    public bool PremiumRequiredForPm { get; set; }
    public long UserId { get; set; }

    public void ComputeFlag()
    {
        if (PremiumWouldAllowInvite) { Flags[0] = true; }
        if (PremiumRequiredForPm) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(UserId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { PremiumWouldAllowInvite = true; }
        if (Flags[1]) { PremiumRequiredForPm = true; }
        UserId = reader.ReadInt64();
    }
}