// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputStarsTransaction" />
///</summary>
[TlObject(0x206ae6d1)]
public sealed class TInputStarsTransaction : IInputStarsTransaction
{
    public uint ConstructorId => 0x206ae6d1;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Refund { get; set; }
    public string Id { get; set; }

    public void ComputeFlag()
    {
        if (Refund) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Id);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Refund = true; }
        Id = reader.ReadString();
    }
}