// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputQuickReplyShortcut" />
///</summary>
[TlObject(0x24596d41)]
public sealed class TInputQuickReplyShortcut : IInputQuickReplyShortcut
{
    public uint ConstructorId => 0x24596d41;
    public string Shortcut { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Shortcut);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Shortcut = reader.ReadString();
    }
}