// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateStarsRevenueStatus" />
///</summary>
[TlObject(0xa584b019)]
public sealed class TUpdateStarsRevenueStatus : IUpdate
{
    public uint ConstructorId => 0xa584b019;
    public MyTelegram.Schema.IPeer Peer { get; set; }
    public MyTelegram.Schema.IStarsRevenueStatus Status { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(Status);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Peer = reader.Read<MyTelegram.Schema.IPeer>();
        Status = reader.Read<MyTelegram.Schema.IStarsRevenueStatus>();
    }
}