// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateDeleteQuickReply" />
///</summary>
[TlObject(0x53e6f1ec)]
public sealed class TUpdateDeleteQuickReply : IUpdate
{
    public uint ConstructorId => 0x53e6f1ec;
    public int ShortcutId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ShortcutId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ShortcutId = reader.ReadInt32();
    }
}