// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateBotBusinessConnect" />
///</summary>
[TlObject(0x8ae5c97a)]
public sealed class TUpdateBotBusinessConnect : IUpdate
{
    public uint ConstructorId => 0x8ae5c97a;
    public MyTelegram.Schema.IBotBusinessConnection Connection { get; set; }
    public int Qts { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Connection);
        writer.Write(Qts);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Connection = reader.Read<MyTelegram.Schema.IBotBusinessConnection>();
        Qts = reader.ReadInt32();
    }
}