// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateSmsJob" />
///</summary>
[TlObject(0xf16269d4)]
public sealed class TUpdateSmsJob : IUpdate
{
    public uint ConstructorId => 0xf16269d4;
    public string JobId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(JobId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        JobId = reader.ReadString();
    }
}