// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateBroadcastRevenueTransactions" />
///</summary>
[TlObject(0xdfd961f5)]
public sealed class TUpdateBroadcastRevenueTransactions : IUpdate
{
    public uint ConstructorId => 0xdfd961f5;
    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/Peer" />
    ///</summary>
    public MyTelegram.Schema.IPeer Peer { get; set; }

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/BroadcastRevenueBalances" />
    ///</summary>
    public MyTelegram.Schema.IBroadcastRevenueBalances Balances { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(Balances);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Peer = reader.Read<MyTelegram.Schema.IPeer>();
        Balances = reader.Read<MyTelegram.Schema.IBroadcastRevenueBalances>();
    }
}