// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updatePaidReactionPrivacy" />
///</summary>
[TlObject(0x51ca7aec)]
public sealed class TUpdatePaidReactionPrivacy : IUpdate
{
    public uint ConstructorId => 0x51ca7aec;
    public bool Private { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Private);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Private = reader.Read();
    }
}