// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateNewStoryReaction" />
///</summary>
[TlObject(0x1824e40b)]
public sealed class TUpdateNewStoryReaction : IUpdate
{
    public uint ConstructorId => 0x1824e40b;
    public int StoryId { get; set; }
    public MyTelegram.Schema.IPeer Peer { get; set; }
    public MyTelegram.Schema.IReaction Reaction { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(StoryId);
        writer.Write(Peer);
        writer.Write(Reaction);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        StoryId = reader.ReadInt32();
        Peer = reader.Read<MyTelegram.Schema.IPeer>();
        Reaction = reader.Read<MyTelegram.Schema.IReaction>();
    }
}