// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateBotDeleteBusinessMessage" />
///</summary>
[TlObject(0xa02a982e)]
public sealed class TUpdateBotDeleteBusinessMessage : IUpdate
{
    public uint ConstructorId => 0xa02a982e;
    public string ConnectionId { get; set; }
    public MyTelegram.Schema.IPeer Peer { get; set; }
    public TVector<int> Messages { get; set; }
    public int Qts { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ConnectionId);
        writer.Write(Peer);
        writer.Write(Messages);
        writer.Write(Qts);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ConnectionId = reader.ReadString();
        Peer = reader.Read<MyTelegram.Schema.IPeer>();
        Messages = reader.Read<TVector<int>>();
        Qts = reader.ReadInt32();
    }
}