// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateNewQuickReply" />
///</summary>
[TlObject(0xf53da717)]
public sealed class TUpdateNewQuickReply : IUpdate
{
    public uint ConstructorId => 0xf53da717;
    public MyTelegram.Schema.IQuickReply QuickReply { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(QuickReply);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        QuickReply = reader.Read<MyTelegram.Schema.IQuickReply>();
    }
}