// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateBotPurchasedPaidMedia" />
///</summary>
[TlObject(0x283bd312)]
public sealed class TUpdateBotPurchasedPaidMedia : IUpdate
{
    public uint ConstructorId => 0x283bd312;
    public long UserId { get; set; }
    public string Payload { get; set; }
    public int Qts { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(UserId);
        writer.Write(Payload);
        writer.Write(Qts);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        UserId = reader.ReadInt64();
        Payload = reader.ReadString();
        Qts = reader.ReadInt32();
    }
}