// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateQuickReplies" />
///</summary>
[TlObject(0xf9470ab2)]
public sealed class TUpdateQuickReplies : IUpdate
{
    public uint ConstructorId => 0xf9470ab2;
    public TVector<MyTelegram.Schema.IQuickReply> QuickReplies { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(QuickReplies);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        QuickReplies = reader.Read<TVector<MyTelegram.Schema.IQuickReply>>();
    }
}