// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/updateStarsBalance" />
///</summary>
[TlObject(0xfb85198)]
public sealed class TUpdateStarsBalance : IUpdate
{
    public uint ConstructorId => 0xfb85198;
    ///<summary>
    /// &nbsp;
    ///</summary>
    public long Balance { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Balance);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Balance = reader.ReadInt64();
    }
}