// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputStorePaymentStars" />
///</summary>
[TlObject(0x4f0ee8df)]
public sealed class TInputStorePaymentStars : IInputStorePaymentPurpose
{
    public uint ConstructorId => 0x4f0ee8df;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// &nbsp;
    ///</summary>
    public long Stars { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public string Currency { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public long Amount { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Stars);
        writer.Write(Currency);
        writer.Write(Amount);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Stars = reader.ReadInt64();
        Currency = reader.ReadString();
        Amount = reader.ReadInt64();
    }
}