// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/mediaAreaUrl" />
///</summary>
[TlObject(0x37381085)]
public sealed class TMediaAreaUrl : IMediaArea
{
    public uint ConstructorId => 0x37381085;
    public MyTelegram.Schema.IMediaAreaCoordinates Coordinates { get; set; }
    public string Url { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Coordinates);
        writer.Write(Url);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Coordinates = reader.Read<MyTelegram.Schema.IMediaAreaCoordinates>();
        Url = reader.ReadString();
    }
}