// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/quickReply" />
///</summary>
[TlObject(0x697102b)]
public sealed class TQuickReply : IQuickReply
{
    public uint ConstructorId => 0x697102b;
    public int ShortcutId { get; set; }
    public string Shortcut { get; set; }
    public int TopMessage { get; set; }
    public int Count { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ShortcutId);
        writer.Write(Shortcut);
        writer.Write(TopMessage);
        writer.Write(Count);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ShortcutId = reader.ReadInt32();
        Shortcut = reader.ReadString();
        TopMessage = reader.ReadInt32();
        Count = reader.ReadInt32();
    }
}