// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Contacts;

///<summary>
/// See <a href="https://corefork.telegram.org/method/contacts.getBirthdays" />
///</summary>
[TlObject(0xdaeda864)]
public sealed class RequestGetBirthdays : IRequest<MyTelegram.Schema.Contacts.IContactBirthdays>
{
    public uint ConstructorId => 0xdaeda864;

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}
