// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Contacts;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/contacts.contactBirthdays" />
///</summary>
[TlObject(0x114ff30d)]
public sealed class TContactBirthdays : IContactBirthdays
{
    public uint ConstructorId => 0x114ff30d;
    public TVector<MyTelegram.Schema.IContactBirthday> Contacts { get; set; }
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Contacts);
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Contacts = reader.Read<TVector<MyTelegram.Schema.IContactBirthday>>();
        Users = reader.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}