// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/smsJob" />
///</summary>
[TlObject(0xe6a1eeb8)]
public sealed class TSmsJob : ISmsJob
{
    public uint ConstructorId => 0xe6a1eeb8;
    public string JobId { get; set; }
    public string PhoneNumber { get; set; }
    public string Text { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(JobId);
        writer.Write(PhoneNumber);
        writer.Write(Text);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        JobId = reader.ReadString();
        PhoneNumber = reader.ReadString();
        Text = reader.ReadString();
    }
}