// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/requestedPeerChannel" />
///</summary>
[TlObject(0x8ba403e4)]
public sealed class TRequestedPeerChannel : IRequestedPeer
{
    public uint ConstructorId => 0x8ba403e4;
    public BitArray Flags { get; set; } = new BitArray(32);
    public long ChannelId { get; set; }
    public string? Title { get; set; }
    public string? Username { get; set; }
    public MyTelegram.Schema.IPhoto? Photo { get; set; }

    public void ComputeFlag()
    {
        if (Title != null) { Flags[0] = true; }
        if (Username != null) { Flags[1] = true; }
        if (Photo != null) { Flags[2] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(ChannelId);
        if (Flags[0]) { writer.Write(Title); }
        if (Flags[1]) { writer.Write(Username); }
        if (Flags[2]) { writer.Write(Photo); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        ChannelId = reader.ReadInt64();
        if (Flags[0]) { Title = reader.ReadString(); }
        if (Flags[1]) { Username = reader.ReadString(); }
        if (Flags[2]) { Photo = reader.Read<MyTelegram.Schema.IPhoto>(); }
    }
}