// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputBusinessGreetingMessage" />
///</summary>
[TlObject(0x194cb3b)]
public sealed class TInputBusinessGreetingMessage : IInputBusinessGreetingMessage
{
    public uint ConstructorId => 0x194cb3b;
    public int ShortcutId { get; set; }
    public MyTelegram.Schema.IInputBusinessRecipients Recipients { get; set; }
    public int NoActivityDays { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ShortcutId);
        writer.Write(Recipients);
        writer.Write(NoActivityDays);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ShortcutId = reader.ReadInt32();
        Recipients = reader.Read<MyTelegram.Schema.IInputBusinessRecipients>();
        NoActivityDays = reader.ReadInt32();
    }
}