namespace MyTelegram.Domain.ValueObjects;

public record MessageItem //: ValueObject
(Peer OwnerPeer,
        Peer ToPeer,
        Peer SenderPeer,
        long SenderUserId,
        int MessageId,
        string Message,
        int Date,
        long RandomId,
        bool IsOut,
        SendMessageType SendMessageType = SendMessageType.Text,
        MessageType MessageType = MessageType.Text,
        MessageSubType MessageSubType = MessageSubType.Normal,
        IInputReplyTo? InputReplyTo = null,
        string? MessageActionData = null,
        MessageActionType MessageActionType = MessageActionType.None,
        byte[]? Entities = null,
        byte[]? Media = null,
        long? GroupId = null, bool Post = false,
        MessageFwdHeader? FwdHeader = null,
        int? Views = null,
        long? PollId = null,
        byte[]? ReplyMarkup = null,
        long? LinkedChannelId = null,
        int? TopMsgId = null,
        string? PostAuthor = null,
        Peer? SavedPeerId = null,
        Peer? SendAs = null,
        MessageReply? Reply = null,
        bool EditHide = false,
        bool IsForwardFromChannelPost = false,
        long? PostChannelId = null,
        int? PostMessageId = null,
        bool IsQuickReply = false,
        string? QuickReplyShortcut = null,
        Guid? BatchId = null,
        long? Effect = null
        );