// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Auth;

///<summary>
/// See <a href="https://corefork.telegram.org/method/auth.reportMissingCode" />
///</summary>
[TlObject(0xcb9deff6)]
public sealed class RequestReportMissingCode : IRequest<IBool>
{
    public uint ConstructorId => 0xcb9deff6;
    public string PhoneNumber { get; set; }
    public string PhoneCodeHash { get; set; }
    public string Mnc { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(PhoneNumber);
        writer.Write(PhoneCodeHash);
        writer.Write(Mnc);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        PhoneNumber = reader.ReadString();
        PhoneCodeHash = reader.ReadString();
        Mnc = reader.ReadString();
    }
}
