// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messageActionRequestedPeerSentMe" />
///</summary>
[TlObject(0x93b31848)]
public sealed class TMessageActionRequestedPeerSentMe : IMessageAction
{
    public uint ConstructorId => 0x93b31848;
    public int ButtonId { get; set; }
    public TVector<MyTelegram.Schema.IRequestedPeer> Peers { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ButtonId);
        writer.Write(Peers);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ButtonId = reader.ReadInt32();
        Peers = reader.Read<TVector<MyTelegram.Schema.IRequestedPeer>>();
    }
}