// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messageActionStarGift" />
///</summary>
[TlObject(0x9bb3ef44)]
public sealed class TMessageActionStarGift : IMessageAction
{
    public uint ConstructorId => 0x9bb3ef44;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool NameHidden { get; set; }
    public bool Saved { get; set; }
    public bool Converted { get; set; }
    public MyTelegram.Schema.IStarGift Gift { get; set; }
    public MyTelegram.Schema.ITextWithEntities? Message { get; set; }
    public long ConvertStars { get; set; }

    public void ComputeFlag()
    {
        if (NameHidden) { Flags[0] = true; }
        if (Saved) { Flags[2] = true; }
        if (Converted) { Flags[3] = true; }
        if (Message != null) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Gift);
        if (Flags[1]) { writer.Write(Message); }
        writer.Write(ConvertStars);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { NameHidden = true; }
        if (Flags[2]) { Saved = true; }
        if (Flags[3]) { Converted = true; }
        Gift = reader.Read<MyTelegram.Schema.IStarGift>();
        if (Flags[1]) { Message = reader.Read<MyTelegram.Schema.ITextWithEntities>(); }
        ConvertStars = reader.ReadInt64();
    }
}