// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messageActionPrizeStars" />
///</summary>
[TlObject(0xb00c47a2)]
public sealed class TMessageActionPrizeStars : IMessageAction
{
    public uint ConstructorId => 0xb00c47a2;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Unclaimed { get; set; }
    public long Stars { get; set; }
    public string TransactionId { get; set; }
    public MyTelegram.Schema.IPeer BoostPeer { get; set; }
    public int GiveawayMsgId { get; set; }

    public void ComputeFlag()
    {
        if (Unclaimed) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Stars);
        writer.Write(TransactionId);
        writer.Write(BoostPeer);
        writer.Write(GiveawayMsgId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Unclaimed = true; }
        Stars = reader.ReadInt64();
        TransactionId = reader.ReadString();
        BoostPeer = reader.Read<MyTelegram.Schema.IPeer>();
        GiveawayMsgId = reader.ReadInt32();
    }
}