// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// A <a href="https://corefork.telegram.org/api/giveaways">giveaway</a> was started.
/// See <a href="https://corefork.telegram.org/constructor/messageActionGiveawayLaunch" />
///</summary>
[TlObject(0xa80f51e4)]
public sealed class TMessageActionGiveawayLaunch : IMessageAction
{
    public uint ConstructorId => 0xa80f51e4;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// For <a href="https://corefork.telegram.org/api/stars#star-giveaways">Telegram Star giveaways</a>, the total number of Telegram Stars being given away.
    ///</summary>
    public long? Stars { get; set; }

    public void ComputeFlag()
    {
        if (/*Stars != 0 &&*/ Stars.HasValue) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[0]) { writer.Write(Stars.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Stars = reader.ReadInt64(); }
    }
}