// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Handlers.Channels;

public interface IGetChannelRecommendationsHandler : IObjectHandler
{
}

public interface IGetChannelRecommendationsHandler2 : IObjectHandler
{
}