// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/businessChatLink" />
///</summary>
[TlObject(0xb4ae666f)]
public sealed class TBusinessChatLink : IBusinessChatLink
{
    public uint ConstructorId => 0xb4ae666f;
    public BitArray Flags { get; set; } = new BitArray(32);
    public string Link { get; set; }
    public string Message { get; set; }
    public TVector<MyTelegram.Schema.IMessageEntity>? Entities { get; set; }
    public string? Title { get; set; }
    public int Views { get; set; }

    public void ComputeFlag()
    {
        if (Entities?.Count > 0) { Flags[0] = true; }
        if (Title != null) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Link);
        writer.Write(Message);
        if (Flags[0]) { writer.Write(Entities); }
        if (Flags[1]) { writer.Write(Title); }
        writer.Write(Views);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Link = reader.ReadString();
        Message = reader.ReadString();
        if (Flags[0]) { Entities = reader.Read<TVector<MyTelegram.Schema.IMessageEntity>>(); }
        if (Flags[1]) { Title = reader.ReadString(); }
        Views = reader.ReadInt32();
    }
}