// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/businessWorkHours" />
///</summary>
[TlObject(0x8c92b098)]
public sealed class TBusinessWorkHours : IBusinessWorkHours
{
    public uint ConstructorId => 0x8c92b098;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool OpenNow { get; set; }
    public string TimezoneId { get; set; }
    public TVector<MyTelegram.Schema.IBusinessWeeklyOpen> WeeklyOpen { get; set; }

    public void ComputeFlag()
    {
        if (OpenNow) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(TimezoneId);
        writer.Write(WeeklyOpen);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { OpenNow = true; }
        TimezoneId = reader.ReadString();
        WeeklyOpen = reader.Read<TVector<MyTelegram.Schema.IBusinessWeeklyOpen>>();
    }
}