// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/botBusinessConnection" />
///</summary>
[TlObject(0x896433b4)]
public sealed class TBotBusinessConnection : IBotBusinessConnection
{
    public uint ConstructorId => 0x896433b4;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool CanReply { get; set; }
    public bool Disabled { get; set; }
    public string ConnectionId { get; set; }
    public long UserId { get; set; }
    public int DcId { get; set; }
    public int Date { get; set; }

    public void ComputeFlag()
    {
        if (CanReply) { Flags[0] = true; }
        if (Disabled) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(ConnectionId);
        writer.Write(UserId);
        writer.Write(DcId);
        writer.Write(Date);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { CanReply = true; }
        if (Flags[1]) { Disabled = true; }
        ConnectionId = reader.ReadString();
        UserId = reader.ReadInt64();
        DcId = reader.ReadInt32();
        Date = reader.ReadInt32();
    }
}