// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputCollectibleUsername" />
///</summary>
[TlObject(0xe39460a9)]
public sealed class TInputCollectibleUsername : IInputCollectible
{
    public uint ConstructorId => 0xe39460a9;
    public string Username { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Username);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Username = reader.ReadString();
    }
}