// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputCollectiblePhone" />
///</summary>
[TlObject(0xa2e214a4)]
public sealed class TInputCollectiblePhone : IInputCollectible
{
    public uint ConstructorId => 0xa2e214a4;
    public string Phone { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Phone);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Phone = reader.ReadString();
    }
}