// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/broadcastRevenueBalances" />
///</summary>
[TlObject(0x8438f1c6)]
public sealed class TBroadcastRevenueBalances : IBroadcastRevenueBalances
{
    public uint ConstructorId => 0x8438f1c6;
    public long CurrentBalance { get; set; }
    public long AvailableBalance { get; set; }
    public long OverallRevenue { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(CurrentBalance);
        writer.Write(AvailableBalance);
        writer.Write(OverallRevenue);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        CurrentBalance = reader.ReadInt64();
        AvailableBalance = reader.ReadInt64();
        OverallRevenue = reader.ReadInt64();
    }
}