// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/privacyValueAllowPremium" />
///</summary>
[TlObject(0xece9814b)]
public sealed class TPrivacyValueAllowPremium : IPrivacyRule
{
    public uint ConstructorId => 0xece9814b;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}