// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starsSubscriptionPricing" />
///</summary>
[TlObject(0x5416d58)]
public sealed class TStarsSubscriptionPricing : IStarsSubscriptionPricing
{
    public uint ConstructorId => 0x5416d58;
    public int Period { get; set; }
    public long Amount { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Period);
        writer.Write(Amount);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Period = reader.ReadInt32();
        Amount = reader.ReadInt64();
    }
}