// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/geoPointAddress" />
///</summary>
[TlObject(0xde4c5d93)]
public sealed class TGeoPointAddress : IGeoPointAddress
{
    public uint ConstructorId => 0xde4c5d93;
    public BitArray Flags { get; set; } = new BitArray(32);
    public string CountryIso2 { get; set; }
    public string? State { get; set; }
    public string? City { get; set; }
    public string? Street { get; set; }

    public void ComputeFlag()
    {
        if (State != null) { Flags[0] = true; }
        if (City != null) { Flags[1] = true; }
        if (Street != null) { Flags[2] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(CountryIso2);
        if (Flags[0]) { writer.Write(State); }
        if (Flags[1]) { writer.Write(City); }
        if (Flags[2]) { writer.Write(Street); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        CountryIso2 = reader.ReadString();
        if (Flags[0]) { State = reader.ReadString(); }
        if (Flags[1]) { City = reader.ReadString(); }
        if (Flags[2]) { Street = reader.ReadString(); }
    }
}