// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Help;

///<summary>
/// See <a href="https://corefork.telegram.org/method/help.getTimezonesList" />
///</summary>
[TlObject(0x49b30240)]
public sealed class RequestGetTimezonesList : IRequest<MyTelegram.Schema.Help.ITimezonesList>
{
    public uint ConstructorId => 0x49b30240;
    public int Hash { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Hash);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Hash = reader.ReadInt32();
    }
}
