// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Help;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/help.timezonesList" />
///</summary>
[TlObject(0x7b74ed71)]
public sealed class TTimezonesList : ITimezonesList
{
    public uint ConstructorId => 0x7b74ed71;
    public TVector<MyTelegram.Schema.ITimezone> Timezones { get; set; }
    public int Hash { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Timezones);
        writer.Write(Hash);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Timezones = reader.Read<TVector<MyTelegram.Schema.ITimezone>>();
        Hash = reader.ReadInt32();
    }
}