// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starsTransactionPeerFragment" />
///</summary>
[TlObject(0xe92fd902)]
public sealed class TStarsTransactionPeerFragment : IStarsTransactionPeer
{
    public uint ConstructorId => 0xe92fd902;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}