// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starsTransactionPeerPlayMarket" />
///</summary>
[TlObject(0x7b560a0b)]
public sealed class TStarsTransactionPeerPlayMarket : IStarsTransactionPeer
{
    public uint ConstructorId => 0x7b560a0b;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}