// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starGift" />
///</summary>
[TlObject(0x49c577cd)]
public sealed class TStarGift : IStarGift
{
    public uint ConstructorId => 0x49c577cd;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Limited { get; set; }
    public bool SoldOut { get; set; }
    public long Id { get; set; }
    public MyTelegram.Schema.IDocument Sticker { get; set; }
    public long Stars { get; set; }
    public int? AvailabilityRemains { get; set; }
    public int? AvailabilityTotal { get; set; }
    public long ConvertStars { get; set; }
    public int? FirstSaleDate { get; set; }
    public int? LastSaleDate { get; set; }

    public void ComputeFlag()
    {
        if (Limited) { Flags[0] = true; }
        if (SoldOut) { Flags[1] = true; }
        if (/*AvailabilityRemains != 0 && */AvailabilityRemains.HasValue) { Flags[0] = true; }
        if (/*AvailabilityTotal != 0 && */AvailabilityTotal.HasValue) { Flags[0] = true; }
        if (/*FirstSaleDate != 0 && */FirstSaleDate.HasValue) { Flags[1] = true; }
        if (/*LastSaleDate != 0 && */LastSaleDate.HasValue) { Flags[1] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Id);
        writer.Write(Sticker);
        writer.Write(Stars);
        if (Flags[0]) { writer.Write(AvailabilityRemains.Value); }
        if (Flags[0]) { writer.Write(AvailabilityTotal.Value); }
        writer.Write(ConvertStars);
        if (Flags[1]) { writer.Write(FirstSaleDate.Value); }
        if (Flags[1]) { writer.Write(LastSaleDate.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Limited = true; }
        if (Flags[1]) { SoldOut = true; }
        Id = reader.ReadInt64();
        Sticker = reader.Read<MyTelegram.Schema.IDocument>();
        Stars = reader.ReadInt64();
        if (Flags[0]) { AvailabilityRemains = reader.ReadInt32(); }
        if (Flags[0]) { AvailabilityTotal = reader.ReadInt32(); }
        ConvertStars = reader.ReadInt64();
        if (Flags[1]) { FirstSaleDate = reader.ReadInt32(); }
        if (Flags[1]) { LastSaleDate = reader.ReadInt32(); }
    }
}