// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/businessWeeklyOpen" />
///</summary>
[TlObject(0x120b1ab9)]
public sealed class TBusinessWeeklyOpen : IBusinessWeeklyOpen
{
    public uint ConstructorId => 0x120b1ab9;
    public int StartMinute { get; set; }
    public int EndMinute { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(StartMinute);
        writer.Write(EndMinute);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        StartMinute = reader.ReadInt32();
        EndMinute = reader.ReadInt32();
    }
}