// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputInvoiceStarGift" />
///</summary>
[TlObject(0x25d8c1d8)]
public sealed class TInputInvoiceStarGift : IInputInvoice
{
    public uint ConstructorId => 0x25d8c1d8;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool HideName { get; set; }
    public MyTelegram.Schema.IInputUser UserId { get; set; }
    public long GiftId { get; set; }
    public MyTelegram.Schema.ITextWithEntities? Message { get; set; }

    public void ComputeFlag()
    {
        if (HideName) { Flags[0] = true; }
        if (Message != null) { Flags[1] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(UserId);
        writer.Write(GiftId);
        if (Flags[1]) { writer.Write(Message); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { HideName = true; }
        UserId = reader.Read<MyTelegram.Schema.IInputUser>();
        GiftId = reader.ReadInt64();
        if (Flags[1]) { Message = reader.Read<MyTelegram.Schema.ITextWithEntities>(); }
    }
}