// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputInvoiceChatInviteSubscription" />
///</summary>
[TlObject(0x34e793f1)]
public sealed class TInputInvoiceChatInviteSubscription : IInputInvoice
{
    public uint ConstructorId => 0x34e793f1;
    public string Hash { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Hash);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Hash = reader.ReadString();
    }
}