global using EventFlow;
global using EventFlow.Extensions;
global using EventFlow.Queries;
global using MyTelegram.Domain.Aggregates.AuthKey;
global using MyTelegram.Domain.Aggregates.Blocked;
//global using MyTelegram.Domain.Aggregates.Bot;
global using MyTelegram.Domain.Aggregates.Channel;
global using MyTelegram.Domain.Aggregates.Chat;
global using MyTelegram.Domain.Aggregates.Contact;
global using MyTelegram.Domain.Aggregates.Device;
global using MyTelegram.Domain.Aggregates.EncryptedChat;
global using MyTelegram.Domain.Aggregates.PhoneCall;
global using MyTelegram.Domain.Aggregates.Privacy;
global using MyTelegram.Domain.Aggregates.Pts;
global using MyTelegram.Domain.Aggregates.User;
global using MyTelegram.Domain.Aggregates.UserName;
global using MyTelegram.Domain.Aggregates.UserPassword;
global using MyTelegram.Domain.ValueObjects;
global using MyTelegram.Queries;
global using MyTelegram.ReadModel;
global using MyTelegram.ReadModel.Impl;
global using System.Linq.Expressions;
global using MyTelegram.QueryHandlers.InMemory;

global using MyTelegram.EventFlow.ReadStores;
global using AppCodeReadModel = MyTelegram.ReadModel.InMemory.AppCodeReadModel;
global using AuthKeyReadModel = MyTelegram.ReadModel.InMemory.AuthKeyReadModel;
global using BlockedReadModel = MyTelegram.ReadModel.InMemory.BlockedReadModel;
//global using BotReadModel = MyTelegram.ReadModel.InMemory.BotReadModel;
global using ChannelFullReadModel = MyTelegram.ReadModel.InMemory.ChannelFullReadModel;
global using ChannelMemberReadModel = MyTelegram.ReadModel.InMemory.ChannelMemberReadModel;
global using ChannelReadModel = MyTelegram.ReadModel.InMemory.ChannelReadModel;
global using ChatInviteReadModel = MyTelegram.ReadModel.InMemory.ChatInviteReadModel;
global using ChatReadModel = MyTelegram.ReadModel.InMemory.ChatReadModel;
global using ContactReadModel = MyTelegram.ReadModel.InMemory.ContactReadModel;
global using DeviceReadModel = MyTelegram.ReadModel.InMemory.DeviceReadModel;
global using DialogReadModel = MyTelegram.ReadModel.InMemory.DialogReadModel;
global using DraftReadModel = MyTelegram.ReadModel.InMemory.DraftReadModel;
global using EncryptedChatReadModel = MyTelegram.ReadModel.InMemory.EncryptedChatReadModel;
global using EncryptedPushUpdatesReadModel = MyTelegram.ReadModel.InMemory.EncryptedPushUpdatesReadModel;
global using FileReadModel = MyTelegram.ReadModel.InMemory.FileReadModel;
global using MessageReadModel = MyTelegram.ReadModel.InMemory.MessageReadModel;
global using PeerNotifySettingsReadModel = MyTelegram.ReadModel.InMemory.PeerNotifySettingsReadModel;
global using PhoneCallConfigReadModel = MyTelegram.ReadModel.InMemory.PhoneCallConfigReadModel;
global using PrivacyReadModel = MyTelegram.ReadModel.InMemory.PrivacyReadModel;
global using PtsForAuthKeyIdReadModel = MyTelegram.ReadModel.InMemory.PtsForAuthKeyIdReadModel;
global using PtsReadModel = MyTelegram.ReadModel.InMemory.PtsReadModel;
//global using PushUpdatesReadModel = MyTelegram.ReadModel.InMemory.PushUpdatesReadModel;
global using ReadingHistoryReadModel = MyTelegram.ReadModel.InMemory.ReadingHistoryReadModel;
global using RpcResultReadModel = MyTelegram.ReadModel.InMemory.RpcResultReadModel;
global using UserNameReadModel = MyTelegram.ReadModel.InMemory.UserNameReadModel;
global using UserPasswordReadModel = MyTelegram.ReadModel.InMemory.UserPasswordReadModel;
global using UserReadModel = MyTelegram.ReadModel.InMemory.UserReadModel;
global using ReplyReadModel = MyTelegram.ReadModel.InMemory.ReplyReadModel;
global using DialogFilterReadModel = MyTelegram.ReadModel.InMemory.DialogFilterReadModel;
global using PollReadModel = MyTelegram.ReadModel.InMemory.PollReadModel;
global using PollAnswerVoterReadModel = MyTelegram.ReadModel.InMemory.PollAnswerVoterReadModel;
global using LoginLogReadModel = MyTelegram.ReadModel.InMemory.LoginLogReadModel;
global using UserReactionReadModel = MyTelegram.ReadModel.InMemory.UserReactionReadModel;
global using ForumTopicReadModel = MyTelegram.ReadModel.InMemory.ForumTopicReadModel;
global using AccessHashReadModel = MyTelegram.ReadModel.InMemory.AccessHashReadModel;
global using PeerSettingsReadModel = MyTelegram.ReadModel.InMemory.PeerSettingsReadModel;
global using PhotoReadModel = MyTelegram.ReadModel.InMemory.PhotoReadModel;
global using ChatAdminReadModel = MyTelegram.ReadModel.InMemory.ChatAdminReadModel;
global using ChannelAdminLogEventReadModel = MyTelegram.ReadModel.InMemory.ChannelAdminLogEventReadModel;
global using ChatInviteImporterReadModel = MyTelegram.ReadModel.InMemory.ChatInviteImporterReadModel;
global using MentionsReadModel = MyTelegram.ReadModel.InMemory.MentionsReadModel;
global using UpdatesReadModel = MyTelegram.ReadModel.InMemory.UpdatesReadModel;
global using EncryptedMessageReadModel = MyTelegram.ReadModel.InMemory.EncryptedMessageReadModel;
