// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Stickers;

///<summary>
/// See <a href="https://corefork.telegram.org/method/stickers.replaceSticker" />
///</summary>
[TlObject(0x4696459a)]
public sealed class RequestReplaceSticker : IRequest<MyTelegram.Schema.Messages.IStickerSet>
{
    public uint ConstructorId => 0x4696459a;
    public MyTelegram.Schema.IInputDocument Sticker { get; set; }
    public MyTelegram.Schema.IInputStickerSetItem NewSticker { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Sticker);
        writer.Write(NewSticker);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Sticker = reader.Read<MyTelegram.Schema.IInputDocument>();
        NewSticker = reader.Read<MyTelegram.Schema.IInputStickerSetItem>();
    }
}
