// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/webPageAttributeStickerSet" />
///</summary>
[TlObject(0x50cc03d3)]
public sealed class TWebPageAttributeStickerSet : IWebPageAttribute
{
    public uint ConstructorId => 0x50cc03d3;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Emojis { get; set; }
    public bool TextColor { get; set; }
    public TVector<MyTelegram.Schema.IDocument> Stickers { get; set; }

    public void ComputeFlag()
    {
        if (Emojis) { Flags[0] = true; }
        if (TextColor) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Stickers);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Emojis = true; }
        if (Flags[1]) { TextColor = true; }
        Stickers = reader.Read<TVector<MyTelegram.Schema.IDocument>>();
    }
}