// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/connectedBot" />
///</summary>
[TlObject(0xbd068601)]
public sealed class TConnectedBot : IConnectedBot
{
    public uint ConstructorId => 0xbd068601;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool CanReply { get; set; }
    public long BotId { get; set; }
    public MyTelegram.Schema.IBusinessBotRecipients Recipients { get; set; }

    public void ComputeFlag()
    {
        if (CanReply) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(BotId);
        writer.Write(Recipients);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { CanReply = true; }
        BotId = reader.ReadInt64();
        Recipients = reader.Read<MyTelegram.Schema.IBusinessBotRecipients>();
    }
}