// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// A <a href="https://core.telegram.org/api/sponsored-messages">sponsored message</a>.
/// See <a href="https://corefork.telegram.org/constructor/sponsoredMessage" />
///</summary>
[TlObject(0xbdedf566)]
public sealed class TSponsoredMessage : ISponsoredMessage
{
    public uint ConstructorId => 0xbdedf566;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// Whether the message needs to be labeled as "recommended" instead of "sponsored"
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool Recommended { get; set; }
    public bool CanReport { get; set; }

    ///<summary>
    /// Message ID
    ///</summary>
    public byte[] RandomId { get; set; }
    public string Url { get; set; }
    public string Title { get; set; }

    ///<summary>
    /// Sponsored message
    ///</summary>
    public string Message { get; set; }

    ///<summary>
    /// <a href="https://corefork.telegram.org/api/entities">Message entities for styled text</a>
    ///</summary>
    public TVector<MyTelegram.Schema.IMessageEntity>? Entities { get; set; }
    public MyTelegram.Schema.IPhoto? Photo { get; set; }
    public MyTelegram.Schema.IPeerColor? Color { get; set; }

    ///<summary>
    /// Text of the sponsored message button.
    ///</summary>
    public string ButtonText { get; set; }

    ///<summary>
    /// If set, contains additional information about the sponsor to be shown along with the message.
    ///</summary>
    public string? SponsorInfo { get; set; }

    ///<summary>
    /// If set, contains additional information about the sponsored message to be shown along with the message.
    ///</summary>
    public string? AdditionalInfo { get; set; }

    public void ComputeFlag()
    {
        if (Recommended) { Flags[5] = true; }
        if (CanReport) { Flags[12] = true; }
        if (Entities?.Count > 0) { Flags[1] = true; }
        if (Photo != null) { Flags[6] = true; }
        if (Color != null) { Flags[13] = true; }
        if (SponsorInfo != null) { Flags[7] = true; }
        if (AdditionalInfo != null) { Flags[8] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(RandomId);
        writer.Write(Url);
        writer.Write(Title);
        writer.Write(Message);
        if (Flags[1]) { writer.Write(Entities); }
        if (Flags[6]) { writer.Write(Photo); }
        if (Flags[13]) { writer.Write(Color); }
        writer.Write(ButtonText);
        if (Flags[7]) { writer.Write(SponsorInfo); }
        if (Flags[8]) { writer.Write(AdditionalInfo); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[5]) { Recommended = true; }
        if (Flags[12]) { CanReport = true; }
        RandomId = reader.ReadBytes();
        Url = reader.ReadString();
        Title = reader.ReadString();
        Message = reader.ReadString();
        if (Flags[1]) { Entities = reader.Read<TVector<MyTelegram.Schema.IMessageEntity>>(); }
        if (Flags[6]) { Photo = reader.Read<MyTelegram.Schema.IPhoto>(); }
        if (Flags[13]) { Color = reader.Read<MyTelegram.Schema.IPeerColor>(); }
        ButtonText = reader.ReadString();
        if (Flags[7]) { SponsorInfo = reader.ReadString(); }
        if (Flags[8]) { AdditionalInfo = reader.ReadString(); }
    }
}