// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/businessAwayMessageScheduleOutsideWorkHours" />
///</summary>
[TlObject(0xc3f2f501)]
public sealed class TBusinessAwayMessageScheduleOutsideWorkHours : IBusinessAwayMessageSchedule
{
    public uint ConstructorId => 0xc3f2f501;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}