// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/businessAwayMessageScheduleAlways" />
///</summary>
[TlObject(0xc9b9e2b9)]
public sealed class TBusinessAwayMessageScheduleAlways : IBusinessAwayMessageSchedule
{
    public uint ConstructorId => 0xc9b9e2b9;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}