// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/businessAwayMessageScheduleCustom" />
///</summary>
[TlObject(0xcc4d9ecc)]
public sealed class TBusinessAwayMessageScheduleCustom : IBusinessAwayMessageSchedule
{
    public uint ConstructorId => 0xcc4d9ecc;
    public int StartDate { get; set; }
    public int EndDate { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(StartDate);
        writer.Write(EndDate);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        StartDate = reader.ReadInt32();
        EndDate = reader.ReadInt32();
    }
}