// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starsGiveawayWinnersOption" />
///</summary>
[TlObject(0x54236209)]
public sealed class TStarsGiveawayWinnersOption : IStarsGiveawayWinnersOption
{
    public uint ConstructorId => 0x54236209;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Default { get; set; }
    public int Users { get; set; }
    public long PerUserStars { get; set; }

    public void ComputeFlag()
    {
        if (Default) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Users);
        writer.Write(PerUserStars);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Default = true; }
        Users = reader.ReadInt32();
        PerUserStars = reader.ReadInt64();
    }
}